name: Continuous Integration

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build Docker Image
        run: |
          docker build -t gen-bef1314b-eae5-4ec5-8c2b-8bc9f1d6db06 .
      
      - name: Run Unit Tests
        run: go test ./... -v

      - name: Run Integration Tests
        run: go test ./integration -v

      - name: Run Load Tests
        run: go test ./load -v

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag gen-bef1314b-eae5-4ec5-8c2b-8bc9f1d6db06 ${{ secrets.DOCKER_USERNAME }}/gen-bef1314b-eae5-4ec5-8c2b-8bc9f1d6db06:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gen-bef1314b-eae5-4ec5-8c2b-8bc9f1d6db06:latest

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/gen-bef1314b-eae5-4ec5-8c2b-8bc9f1d6db06